# Basic Usage of Calysto Scheme

## Writing math equation

$
\sin\left(\frac{\pi}{2}\right) = 1
$

In [1]:
(import "math")
(math.sin (/ math.pi 2) )

1.0

In [2]:
(define (sum term a next b)
    (if (> a b)
        0
        (+ (term a)
    (sum term (next a) next b))))


(define (integral f a b dx)
    (* (sum 
            f
            (+ a (/ dx 2.0))
            (lambda (x) (+ x dx))
            b
        )
        dx))

$
\int_0^{\pi}{\sin x dx} = \left[-\cos x\right]_0^{\pi}=2
$

In [3]:
(integral math.sin 0 math.pi 0.001)

2.0000000003679608

## dict and sequence

In [4]:
(dict '((a : 1)(b : 2)))

{a: 1, b: 2}

In [5]:
(list 1 2 3)

(1 2 3)

In [6]:
(type (list 1 2 3))

class 'calysto_scheme.scheme.cons'

In [7]:
(dir (list 1 2 3))

(__call__ __class__ __delattr__ __dict__ __dir__ __doc__ __eq__ __format__ __ge__ __getattribute__ __getitem__ __gt__ __hash__ __init__ __init_subclass__ __iter__ __le__ __len__ __lt__ __module__ __ne__ __new__ __next__ __reduce__ __reduce_ex__ __repr__ __setattr__ __sizeof__ __str__ __subclasshook__ __weakref__ car cdr next)

In [8]:
(type (dict '((a : 1)(b : 2))))

class 'dict'

In [9]:
(define l (list 1 2 3))
l

(1 2 3)

In [10]:
(get-item l 1)

2

In [11]:
(define d (dict '((a : 1)(b : 2))))
d

{a: 1, b: 2}

In [12]:
(get-item d 'a)

1

In [13]:
(set-item! d 'a 2)
d

{a: 2, b: 2}

## NumPy

In [14]:
(import-as "numpy" 'np)

(np)

In [15]:
; a = np.array([[1, 2], [3, 4]])      in Python
(define a (np.array (list '(1 2) '(3 4))) )

In [16]:
a

array([[1, 2],
       [3, 4]])

In [17]:
a.shape

(2, 2)

In [18]:
; a.reshape((4, 1))    in Python
(a.reshape (list 4 1))

array([[1],
       [2],
       [3],
       [4]])

In [19]:
; b = np.array([[1, 2, 3], [4, 5, 6]]) in Python
(define b (np.array (list '(1 2 3) '(4 5 6))) )

In [20]:
b

array([[1, 2, 3],
       [4, 5, 6]])

$
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{pmatrix} =
\begin{pmatrix}
9 & 12 & 15 \\
19 & 26 & 33 \\
\end{pmatrix}
$

In [21]:
; np.dot(a, b)    in Python
(np.dot a b)

array([[ 9, 12, 15],
       [19, 26, 33]])